apiVersion: v1
kind: Pod
metadata:
  name: i2b2p
  labels:
    name: i2b2p
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "install",
            "image": "busybox",
            "command": ["/bin/sh","-c","echo \"hi\" > /cache/msg; echo \"127.0.0.1 i2b2-pg\" >> /etc/hosts"],
            "volumeMounts": [
                {
                    "name": "workdir",
                    "mountPath": "/cache"
                }
            ]
        }
    ]'


spec:
  containers:
  - name: ipg
    image: i2b2/i2b2-pg:0.5
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    ports:
    - containerPort: 5432
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "printenv;#sleep 10;echo Hello from the postStart handler > /cache/message; export PUBLIC_IP=\"localhost:8080\";sh update_pm_cell_data.sh >> /cache/message; "]
  - name: iwf
    image: i2b2/i2b2-wildfly:0.21
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    env:
    - name: DS_IP
      value: "localhost"
    - name: DS_PORT
      value: "5432"
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /etc1
      name: etc-volume

  volumes:
  - name: cache-volume
    emptyDir: {}
  - name: etc-volume
    emptyDir: {}
  - name: workdir
    emptyDir: {}
  restartPolicy: Never

